"""+comment_thread

Revision ID: 6bc8c9adc076
Revises: 0ca68d34dbcc
Create Date: 2022-10-24 12:18:24.169654

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6bc8c9adc076"
down_revision = "0ca68d34dbcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commentthread",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("comment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commentthread_comment_id"), "commentthread", ["comment_id"], unique=False)
    op.create_index(op.f("ix_commentthread_id"), "commentthread", ["id"], unique=False)
    op.create_index(op.f("ix_commentthread_post_id"), "commentthread", ["post_id"], unique=False)
    op.add_column("comment", sa.Column("attached_to_thread_id", postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f("ix_comment_attached_to_thread_id"), "comment", ["attached_to_thread_id"], unique=False)
    op.create_foreign_key(None, "comment", "commentthread", ["attached_to_thread_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_index(op.f("ix_comment_attached_to_thread_id"), table_name="comment")
    op.drop_column("comment", "attached_to_thread_id")
    op.drop_index(op.f("ix_commentthread_post_id"), table_name="commentthread")
    op.drop_index(op.f("ix_commentthread_id"), table_name="commentthread")
    op.drop_index(op.f("ix_commentthread_comment_id"), table_name="commentthread")
    op.drop_table("commentthread")
    # ### end Alembic commands ###
