"""+upvote polarity

Revision ID: 82e70a3f48ff
Revises: 926e3b4fc20d
Create Date: 2022-10-21 22:41:35.163819

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "82e70a3f48ff"
down_revision = "926e3b4fc20d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("comment", "parent_comment_uuid", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("comment", "parent_comment_uuid", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###
