"""unique username

Revision ID: 926e3b4fc20d
Revises: c6a6bca7ffa8
Create Date: 2022-10-20 16:29:15.691185

"""
import sqlalchemy as sa  # NOQA: F401
import sqlmodel  # NOQA: F401
from alembic import op

# revision identifiers, used by Alembic.
revision = "926e3b4fc20d"
down_revision = "c6a6bca7ffa8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    # ### end Alembic commands ###
