"""+commentthread

Revision ID: a0d19dbb0ee0
Revises: b2f4f7de8453
Create Date: 2022-10-24 00:35:06.080414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0d19dbb0ee0'
down_revision = 'b2f4f7de8453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('attached_to_thread_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('comment', 'attached_thread_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_index(op.f('ix_comment_attached_to_thread_id'), 'comment', ['attached_to_thread_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'commentthread', ['attached_to_thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_attached_to_thread_id'), table_name='comment')
    op.alter_column('comment', 'attached_thread_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('comment', 'attached_to_thread_id')
    # ### end Alembic commands ###
