"""soft-delete posts and comments

Revision ID: a29d9ffec8e0
Revises: ecccc6c13c4b
Create Date: 2022-10-25 21:15:02.859701

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "a29d9ffec8e0"
down_revision = "ecccc6c13c4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("deleted", sa.Boolean(), nullable=False))
    op.add_column("post", sa.Column("deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "deleted")
    op.drop_column("comment", "deleted")
    # ### end Alembic commands ###
