"""+commentthread

Revision ID: b2f4f7de8453
Revises: 65c331ff1e2e
Create Date: 2022-10-24 00:31:40.388260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2f4f7de8453'
down_revision = '65c331ff1e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentthread',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentthread_comment_id'), 'commentthread', ['comment_id'], unique=False)
    op.create_index(op.f('ix_commentthread_id'), 'commentthread', ['id'], unique=False)
    op.create_index(op.f('ix_commentthread_post_id'), 'commentthread', ['post_id'], unique=False)
    op.add_column('comment', sa.Column('attached_thread_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_comment_attached_thread_id'), 'comment', ['attached_thread_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'commentthread', ['attached_thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_attached_thread_id'), table_name='comment')
    op.drop_column('comment', 'attached_thread_id')
    op.drop_index(op.f('ix_commentthread_post_id'), table_name='commentthread')
    op.drop_index(op.f('ix_commentthread_id'), table_name='commentthread')
    op.drop_index(op.f('ix_commentthread_comment_id'), table_name='commentthread')
    op.drop_table('commentthread')
    # ### end Alembic commands ###
